variables:
  GIT_SUBMODULE_STRATEGY: recursive
  BUILD_HELPERS_VERSION: c0d39c0e5a2235262f21d072c4bf3b2dd62b2040
  VMSHED_VERSION: v0.20.1
  VIRTER_VERSION: v0.27.0

stages:
  - build
  - test

build:
   stage: build
   image: $LINBIT_DOCKER_REGISTRY/build-windrbd-1.1
   rules:
     - if: $CI_COMMIT_BRANCH == 'windrbd-1.1'
   script:
     - ./build-windrbd.sh

test:
  tags:
    - libvirt
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH == 'windrbd-1.1'
  script: |
    echo "hallo"
    curl -sSfL -u gitlab-ci-token:$CI_JOB_TOKEN $CI_SERVER_URL/linbit/build-helpers/-/archive/$BUILD_HELPERS_VERSION/ignored.tar.gz | tar -xvzf -
    mv build-helpers-* build-helpers
    . build-helpers/gitlab-utils.sh
    ci_prepare_tools
    ci_fetch_rq
    ci_fetch_binary virter virter-$VIRTER_VERSION https://github.com/LINBIT/virter/releases/download/$VIRTER_VERSION/virter-linux-amd64
    virter --version
    ci_fetch_binary vmshed vmshed-$VMSHED_VERSION https://github.com/LINBIT/vmshed/releases/download/$VMSHED_VERSION/vmshed-linux-amd64
    vmshed --version
    git clone --branch jt/windrbd-support https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/drbd/drbd9-tests.git
    export WINDRBD_VERSION=$CI_COMMIT_BRANCH-from-gitlab
    cd drbd9-tests && ./run-windrbd-tests.sh
  artifacts:
    # provide a convenient name so that the downloaded artifacts can be identified
    name: $CI_PROJECT_NAME-$CI_JOB_ID
    paths:
      - drbd9-tests/tests-out/
    when: always
    reports:
      junit: tests-out/test-results/*.xml

