variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:
  image: $LINBIT_DOCKER_REGISTRY/build-windrbd-1.1

stages:
  - build
  - test

build:
   stage: build
   script:
     - ./build-windrbd.sh

test:
    stage: test
    script:
      - git clone git@gitlab.at.linbit.com:drbd/drbd9-tests.git
      - cd drbd9-tests && ./run-windrbd-tests.sh
