variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test

build:
  stage: build
  image: $LINBIT_DOCKER_REGISTRY/build-windrbd-1.1
  script:
    - ./build-windrbd.sh

test:
  tags:
    - libvirt
  stage: test
  script:
    - echo "hallo"
    - git clone https://gitlab.at.linbit.com/drbd/drbd9-tests.git --branch jt/windrbd-support
    - cd drbd9-tests && ./run-windrbd-tests.sh
