#define COMPAT___VMALLOC_HAS_2_PARAMS
#define COMPAT_ALLOC_WORKQUEUE_TAKES_FMT
/* #undef COMPAT_BEFORE_4_13_KERNEL_READ */
/* #undef COMPAT_BLKDEV_ISSUE_ZEROOUT_DISCARD */
/* #undef COMPAT_CAN_INCLUDE_VERMAGIC_H */
/* #undef COMPAT_DRBD_RELEASE_RETURNS_VOID */
#define COMPAT_GENL_POLICY_IN_OPS
#define COMPAT_HAVE_BIO_MAX_VECS
#define COMPAT_HAVE_CRYPTO_TFM_NEED_KEY
#define COMPAT_HAVE_SHASH_DESC_ON_STACK
/* #undef COMPAT_HAVE_WB_CONGESTED_ENUM */
#define COMPAT_HAVE_ALLOW_KERNEL_SIGNAL
#define COMPAT_HAVE_ATOMIC_DEC_IF_POSITIVE_LINUX
#define COMPAT_HAVE_ATOMIC_IN_FLIGHT
/* #undef COMPAT_HAVE_BD_CLAIM_BY_DISK */
/* #undef COMPAT_HAVE_BD_UNLINK_DISK_HOLDER */
/* #undef COMPAT_HAVE_BDI_CAP_STABLE_WRITES */
/* #undef COMPAT_HAVE_BDI_CONGESTED_FN */
#define COMPAT_HAVE_BIO_BI_BDEV
/* #undef COMPAT_HAVE_BIO_BI_ERROR */
#define COMPAT_HAVE_BIO_BI_OPF
#define COMPAT_HAVE_BIO_BI_STATUS
/* #undef COMPAT_HAVE_BIO_CLONE_FAST */
/* #undef COMPAT_HAVE_BIO_FLUSH */
/* #undef COMPAT_HAVE_BIO_FREE */
/* #undef COMPAT_HAVE_BIO_OP_SHIFT */
/* #undef COMPAT_HAVE_BIO_RW */
#define COMPAT_HAVE_BIO_SET_DEV
/* #undef COMPAT_HAVE_BIO_SET_OP_ATTRS */
#define COMPAT_HAVE_BIO_START_IO_ACCT
/* #undef COMPAT_HAVE_BIOSET_CREATE_FRONT_PAD */
/* #undef COMPAT_HAVE_BIOSET_INIT */
#define COMPAT_HAVE_BIOSET_NEED_BVECS
/* #undef COMPAT_HAVE_BLK_ALLOC_DISK */
/* #undef COMPAT_HAVE_BLK_ALLOC_QUEUE_RH */
#define COMPAT_HAVE_BLK_CHECK_PLUGGED
/* #undef COMPAT_HAVE_BLK_QC_T_MAKE_REQUEST */
/* #undef COMPAT_HAVE_BLK_QUEUE_FLAG_SET */
/* #undef COMPAT_HAVE_BLK_QUEUE_MAKE_REQUEST */
/* #undef COMPAT_HAVE_BLK_QUEUE_MERGE_BVEC */
/* #undef COMPAT_HAVE_BLK_QUEUE_PLUGGED */
/* #undef COMPAT_HAVE_BLK_QUEUE_SPLIT_BIO */
/* #undef COMPAT_HAVE_BLK_QUEUE_SPLIT_Q_BIO */
/* #undef COMPAT_HAVE_BLK_QUEUE_SPLIT_Q_BIO_BIOSET */
/* #undef COMPAT_HAVE_BLK_QUEUE_UPDATE_READAHEAD */
#define COMPAT_HAVE_BLK_QUEUE_WRITE_CACHE
/* #undef COMPAT_HAVE_BLKDEV_GET_BY_PATH */
#define COMPAT_HAVE_D_INODE
#define COMPAT_HAVE_FALLTHROUGH
#define COMPAT_HAVE_FILE_INODE
/* #undef COMPAT_HAVE_GENERIC_START_IO_ACCT_Q_RW_SECT_PART */
/* #undef COMPAT_HAVE_GENERIC_START_IO_ACCT_RW_SECT_PART */
#define COMPAT_HAVE_GENL_FAMILY_PARALLEL_OPS
/* #undef COMPAT_HAVE_HD_STRUCT */
#define COMPAT_HAVE_IB_CQ_INIT_ATTR
/* #undef COMPAT_HAVE_IB_GET_DMA_MR */
#define COMPAT_HAVE_IDR_ALLOC
#define COMPAT_HAVE_IDR_IS_EMPTY
#define COMPAT_HAVE_INODE_LOCK
#define COMPAT_HAVE_KTIME_TO_TIMESPEC64
#define COMPAT_HAVE_KVFREE
#define COMPAT_HAVE_MAX_SEND_RECV_SGE
/* #undef COMPAT_HAVE_NETLINK_CB_PORTID */
/* #undef COMPAT_HAVE_NLA_NEST_START_NOFLAG */
#define COMPAT_HAVE_NLA_PARSE_DEPRECATED
#define COMPAT_HAVE_NLA_PUT_64BIT
#define COMPAT_HAVE_NLA_STRSCPY
#define COMPAT_HAVE_PART_STAT_H
#define COMPAT_HAVE_PART_STAT_READ_ACCUM
/* #undef COMPAT_HAVE_POINTER_BACKING_DEV_INFO */
/* #undef COMPAT_HAVE_PRANDOM_U32 */
#define COMPAT_HAVE_PROC_CREATE_SINGLE
#define COMPAT_HAVE_QUEUE_FLAG_STABLE_WRITES
#define COMPAT_HAVE_RATELIMIT_STATE_INIT
#define COMPAT_HAVE_RB_AUGMENT_FUNCTIONS
#define AUGMENTED_RBTREE_SYMBOLS_EXPORTED
#define COMPAT_HAVE_REFCOUNT_INC
/* #undef COMPAT_HAVE_REQ_FLUSH */
/* #undef COMPAT_HAVE_REQ_HARDBARRIER */
/* #undef COMPAT_HAVE_REQ_NOIDLE */
#define COMPAT_HAVE_REQ_NOUNMAP
#define COMPAT_HAVE_REQ_OP_WRITE
/* #undef COMPAT_HAVE_REQ_OP_WRITE_SAME */
/* #undef COMPAT_HAVE_REQ_OP_WRITE_ZEROES */
#define COMPAT_HAVE_REQ_PRIO
/* #undef COMPAT_HAVE_REQ_WRITE */
/* #undef COMPAT_HAVE_REQ_WRITE_SAME */
/* #undef COMPAT_HAVE_REVALIDATE_DISK_SIZE */
#define COMPAT_HAVE_SCHED_SET_FIFO
/* #undef COMPAT_HAVE_SECURITY_NETLINK_RECV */
#define COMPAT_HAVE_SENDPAGE_OK
/* #undef COMPAT_HAVE_SET_CAPACITY_AND_NOTIFY */
#define COMPAT_HAVE_SHASH_DESC_ZERO
#define COMPAT_HAVE_SIGNED_NLA_PUT
#define COMPAT_HAVE_SIMPLE_POSITIVE
#define COMPAT_HAVE_SOCK_SET_KEEPALIVE
/* #undef COMPAT_HAVE_STRUCT_BVEC_ITER */
/* #undef COMPAT_HAVE_STRUCT_KERNEL_PARAM_OPS */
/* #undef COMPAT_HAVE_STRUCT_SIZE */
#define COMPAT_HAVE_SUBMIT_BIO
/* #undef COMPAT_HAVE_SUBMIT_BIO_NOACCT */
#define COMPAT_HAVE_TCP_SOCK_SET_CORK
#define COMPAT_HAVE_TCP_SOCK_SET_NODELAY
#define COMPAT_HAVE_TCP_SOCK_SET_QUICKACK
#define COMPAT_HAVE_TIME64_TO_TM
#define COMPAT_HAVE_TIMER_SETUP
/* #undef COMPAT_HAVE_VOID_MAKE_REQUEST */
#define COMPAT_HLIST_FOR_EACH_ENTRY_HAS_THREE_PARAMETERS
#define COMPAT_IB_ALLOC_PD_HAS_2_PARAMS
#define COMPAT_IB_DEVICE_HAS_OPS
/* #undef COMPAT_IB_POST_SEND_CONST_PARAMS */
/* #undef COMPAT_IB_QUERY_DEVICE_HAS_3_PARAMS */
#define COMPAT_KMAP_ATOMIC_PAGE_ONLY
/* #undef COMPAT_NEED_MAKE_REQUEST_RECURSION */
#define COMPAT_PART_STAT_READ_TAKES_BLOCK_DEVICE
/* #undef COMPAT_QUEUE_LIMITS_HAS_DISCARD_ZEROES_DATA */
#define COMPAT_RDMA_CREATE_ID_HAS_NET_NS
#define COMPAT_SOCK_CREATE_KERN_HAS_FIVE_PARAMETERS
#define COMPAT_SOCK_OPS_RETURNS_ADDR_LEN
