// This file was generated by bintoc utility
// Binary data from file "partition-table-ok"

#include <stdint.h>

extern uint8_t partition_table_template[1536];
extern int partition_table_template_size;