'\" t
.\"     Title: drbd
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.77.1 <http://docbook.sf.net/>
.\"      Date: 24 June 2014
.\"    Manual: System Administration
.\"    Source: DRBD 9.0.0
.\"  Language: English
.\"
.TH "DRBD" "8" "24 June 2014" "DRBD 9.0.0" "System Administration"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
drbd \- The start and stop script for DRBD
.SH "SYNOPSIS"
.HP \w'\fB/etc/init\&.d/drbd\fR\ 'u
\fB/etc/init\&.d/drbd\fR {start | stop | status | reload | restart | force\-reload}
.SH "INTRODUCTION"
.PP
The
\fB/etc/init\&.d/drbd\fR
script is used to start and stop drbd on a system V style init system\&.
.PP
When using a cluster resource manger such as Pacemaker, DRBD should usually
\fInot\fR
be started by the init system, but should typically be exclusively controlled by the cluster manager\&. You should not use, and disable, the init script in this case\&.
\fBchmod \-x /etc/init\&.d/drbd\fR
has proven most effective for this\&.
.PP
In order to use
\fB/etc/init\&.d/drbd\fR, define a drbd configuration\&. See
\fBdrbd.conf\fR(5)
for details\&.
.SH "VERSION"
.sp
This document was revised for version 9\&.0\&.0 of the DRBD distribution\&.
.SH "AUTHOR"
.sp
Written by Philipp Reisner philipp\&.reisner@linbit\&.com and Lars Ellenberg lars\&.ellenberg@linbit\&.com\&.
.SH "REPORTING BUGS"
.sp
Report bugs to drbd\-user@lists\&.linbit\&.com\&.
.SH "COPYRIGHT"
.sp
Copyright 2001\-2014 LINBIT Information Technologies, Philipp Reisner, Lars Ellenberg\&. This is free software; see the source for copying conditions\&. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&.
.SH "SEE ALSO"
.PP

\fBdrbd.conf\fR(5),
\fBdrbdsetup\fR(8),
\fBdrbdadm\fR(8),
\m[blue]\fBDRBD Homepage\fR\m[]\&\s-2\u[1]\d\s+2
.SH "NOTES"
.IP " 1." 4
DRBD Homepage
.RS 4
\%http://www.drbd.org/
.RE
