#!/bin/bash

for ARG in "$@"; do
    if [[ "$ARG" == *drbd_req.h* ]]; then
	patch $ARG <<'EOF'
diff --git a/drbd/drbd_req.h b/drbd/drbd_req.h
--- a/drbd/drbd_req.h
+++ b/drbd/drbd_req.h
@@ -75,6 +75,10 @@
  *      with or without "success".
  */
 
+#ifdef NOTHING
+#undef NOTHING
+#endif
+
 enum drbd_req_event {
 	CREATED,
 	TO_BE_SENT,
EOF
    fi
done
