# Use this as in:
# OPENSSL_CONF=crypto/openssl-fc44.conf openssl pkcs12 -in crypto/linbit-2019.pfx -nocerts -nodes -legacy -out crypto/linbit-2019.pem
# to create *.pem files (unencrypted private key) from pfx files.
# We need that since modern OpenSSL does not support RC4 (pfx) any
# more until being told to do so.
# We maintain the pem files in the repos, so usually there is nothing
# to do for you.
openssl_conf = openssl_init
[openssl_init]
providers = provider_sect
[provider_sect]
default = default_sect
legacy = legacy_sect
[default_sect]
activate = 1
[legacy_sect]
activate = 1

